server:
  port: 80

logging:
  level:
    root: debug

#shiro:
#  loginUrl: /login.html
#  # Let Shiro Manage the sessions
#  userNativeSessionManager: true
#  # disable URL session rewriting
#  sessionManager:
#    sessionIdUrlRewritingEnabled: false